INSERT INTO
    staff_users(
            staff_user_role,
            staff_user_password
                )
VALUES
    (
     'super_staff_user',
     'super_staff_user_password'
     ),
    (
     'merchandising_staff_user_first',
     'merchandising_password_first'
     ),
    (
     'merchandising_staff_user_second',
     'merchandising_password_second'
     ),
    (
     'inventory_staff_user_first',
     'inventory_password_first'
     ),
    (
     'inventory_staff_user_second',
     'inventory_password_second'
     );
